import { IProduct } from './product.model';

export const PRODUCTS: IProduct[] = [
    {
        id: 1,
        productName: 'product 1',
        productType: 'type 1',
        productCategory: 'category 1',
        isSubCategory: false,
        referenceId: 123,
        password: 'P@ssw0rd',
        deliveryFeesValue: 10,
        deliveryFeesPercent: 2,
      },
      {
        id: 2,
        productName: 'product 2',
        productType: 'type 1',
        productCategory: 'category 2',
        isSubCategory: false,
        referenceId: 456,
        password: 'P@ssw0rd2',
        deliveryFeesValue: 20,
        deliveryFeesPercent: 5,
      }, 
      {
        id: 3,
        productName: 'product 3',
        productType: 'type 1',
        productCategory: 'category 2',
        isSubCategory: false,
        referenceId: 456,
        password: 'P@ssw0rd2',
        deliveryFeesValue: 20,
        deliveryFeesPercent: 5,
      }, {
        id: 4,
        productName: 'product 4',
        productType: 'type 1',
        productCategory: 'category 1',
        isSubCategory: false,
        referenceId: 123,
        password: 'P@ssw0rd',
        deliveryFeesValue: 10,
        deliveryFeesPercent: 2,
      },
      {
        id: 5,
        productName: 'product 5',
        productType: 'type 1',
        productCategory: 'category 2',
        isSubCategory: false,
        referenceId: 456,
        password: 'P@ssw0rd2',
        deliveryFeesValue: 20,
        deliveryFeesPercent: 5,
      },
      {
        id: 6,
        productName: 'product 6',
        productType: 'type 1',
        productCategory: 'category 2',
        isSubCategory: false,
        referenceId: 456,
        password: 'P@ssw0rd2',
        deliveryFeesValue: 20,
        deliveryFeesPercent: 5,
      }, {
        id: 7,
        productName: 'product 7',
        productType: 'type 1',
        productCategory: 'category 1',
        isSubCategory: false,
        referenceId: 123,
        password: 'P@ssw0rd',
        deliveryFeesValue: 10,
        deliveryFeesPercent: 2,
      },
      {
        id: 8,
        productName: 'product 8',
        productType: 'type 1',
        productCategory: 'category 2',
        isSubCategory: false,
        referenceId: 456,
        password: 'P@ssw0rd2',
        deliveryFeesValue: 20,
        deliveryFeesPercent: 5,
      }, {
        id: 9,
        productName: 'product 9',
        productType: 'type 1',
        productCategory: 'category 1',
        isSubCategory: false,
        referenceId: 123,
        password: 'P@ssw0rd',
        deliveryFeesValue: 10,
        deliveryFeesPercent: 2,
      },
      
      {
        id: 10,
        productName: 'product 10',
        productType: 'type 1',
        productCategory: 'category 2',
        isSubCategory: false,
        referenceId: 456,
        password: 'P@ssw0rd2',
        deliveryFeesValue: 20,
        deliveryFeesPercent: 5,
      }, 
];
